// client/src/app/shared/components/confirm-dialog/confirm-dialog.component.ts
import { Component, input, output, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-confirm-dialog',
  standalone: true,
  templateUrl: './confirm-dialog.component.html',
  styleUrl: './confirm-dialog.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ConfirmDialogComponent {
  readonly isOpen = input(false);
  readonly title = input('Confirm Action');
  readonly message = input('Are you sure you want to proceed?');
  readonly confirmLabel = input('Confirm');
  readonly cancelLabel = input('Cancel');
  readonly variant = input<'danger' | 'warning' | 'info'>('danger');

  readonly confirmed = output<void>();
  readonly cancelled = output<void>();

  onConfirm(): void {
    this.confirmed.emit();
  }

  onCancel(): void {
    this.cancelled.emit();
  }
}

@if (isOpen()) {
  <div class="fixed inset-0 z-50 flex items-center justify-center">
    <div class="fixed inset-0 bg-black/50" (click)="onCancel()"></div>
    <div class="relative bg-white rounded-xl shadow-xl z-10 w-full max-w-md mx-4 p-6">
      <div class="flex items-center gap-3 mb-4">
        @if (variant() === 'danger') {
          <div class="w-10 h-10 rounded-full bg-red-100 flex items-center justify-center flex-shrink-0">
            <svg class="w-5 h-5 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
            </svg>
          </div>
        } @else {
          <div class="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center flex-shrink-0">
            <svg class="w-5 h-5 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
        }
        <h3 class="text-lg font-semibold text-gray-900">{{ title() }}</h3>
      </div>
      <p class="text-sm text-gray-600 mb-6">{{ message() }}</p>
      <div class="flex justify-end gap-3">
        <button
          class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
          (click)="onCancel()"
        >
          {{ cancelLabel() }}
        </button>
        <button
          [class]="'px-4 py-2 text-sm font-medium text-white rounded-lg transition-colors ' + (variant() === 'danger' ? 'bg-red-600 hover:bg-red-700' : 'bg-amber-600 hover:bg-amber-700')"
          (click)="onConfirm()"
        >
          {{ confirmLabel() }}
        </button>
      </div>
    </div>
  </div>
}

// bmvfrontend/src/admin/components/ConfirmDialog.tsx
"use client";

import React from "react";
import { Button } from "@/components/ui/button";
import { AlertTriangle, X, Info } from "lucide-react";
import { cn } from "@/lib/utils";
import { Loader2 } from "lucide-react";

interface ConfirmDialogProps {
  isOpen: boolean;
  title: string;
  description: string;
  confirmLabel?: string;
  cancelLabel?: string;
  variant?: "destructive" | "warning" | "info";
  onConfirm: () => void;
  onCancel: () => void;
  loading?: boolean;
}

export function ConfirmDialog({
  isOpen,
  title,
  description,
  confirmLabel = "Confirm",
  cancelLabel = "Cancel",
  variant = "destructive",
  onConfirm,
  onCancel,
  loading = false,
}: ConfirmDialogProps) {
  if (!isOpen) return null;

  const IconComp = variant === "info" ? Info : AlertTriangle;

  const iconBg = {
    destructive: "bg-red-50",
    warning: "bg-amber-50",
    info: "bg-[#E6F1F1]",
  }[variant];

  const iconColor = {
    destructive: "text-red-500",
    warning: "text-amber-500",
    info: "text-[#0D7377]",
  }[variant];

  const confirmBg = {
    destructive: "bg-red-500 hover:bg-red-600",
    warning: "bg-amber-500 hover:bg-amber-600",
    info: "bg-[#0D7377] hover:bg-[#0a5b5e]",
  }[variant];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
        onClick={!loading ? onCancel : undefined}
      />
      {/* Dialog card */}
      <div className="relative z-10 bg-white rounded-2xl shadow-2xl p-6 w-full max-w-sm mx-4 animate-slide-up">
        <button
          onClick={onCancel}
          disabled={loading}
          className="absolute top-4 right-4 h-7 w-7 rounded-lg flex items-center justify-center text-[#70706e] hover:bg-[#F0F0EC] transition-colors"
        >
          <X className="h-4 w-4" />
        </button>

        <div
          className={cn(
            "h-12 w-12 rounded-2xl flex items-center justify-center mb-4",
            iconBg
          )}
        >
          <IconComp className={cn("h-6 w-6", iconColor)} />
        </div>

        <h3 className="text-base font-bold text-[#1A1A19] mb-1">{title}</h3>
        <p className="text-sm text-[#70706e] mb-6 leading-relaxed">
          {description}
        </p>

        <div className="flex gap-3">
          <Button
            variant="outline"
            className="flex-1 border-[#E2E2DE] text-[#70706e] rounded-xl hover:bg-[#F0F0EC]"
            onClick={onCancel}
            disabled={loading}
          >
            {cancelLabel}
          </Button>
          <Button
            className={cn(
              "flex-1 rounded-xl text-white flex items-center gap-1.5",
              confirmBg
            )}
            onClick={onConfirm}
            disabled={loading}
          >
            {loading && <Loader2 className="h-4 w-4 animate-spin" />}
            {loading ? "Processing..." : confirmLabel}
          </Button>
        </div>
      </div>
    </div>
  );
}
