// frontend/src/components/common/Loader.jsx
const Loader = ({ label = "Loading..." }) => {
  return (
    <div
      className="flex flex-col items-center justify-center gap-4 py-20"
      role="status"
      aria-label={label}
    >
      <div className="h-11 w-11 animate-spin rounded-full border-2 border-gray-100 border-t-red-500/70" />
      <p className="text-sm font-medium tracking-wide text-gray-400">{label}</p>
    </div>
  );
};

export default Loader;

// client/src/app/shared/components/loader/loader.component.ts
import { Component, input, computed, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-loader',
  standalone: true,
  templateUrl: './loader.component.html',
  styleUrl: './loader.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoaderComponent {
  readonly size = input<'sm' | 'md' | 'lg'>('md');
  readonly overlay = input(false);
  readonly message = input('');

  readonly spinnerClass = computed(() => {
    const sizes: Record<string, string> = {
      sm: 'w-6 h-6',
      md: 'w-10 h-10',
      lg: 'w-16 h-16',
    };
    return `${sizes[this.size()]} border-4 border-gray-200 border-t-indigo-600 rounded-full animate-spin`;
  });
}

@if (overlay()) {
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-white/80">
    <div class="flex flex-col items-center gap-3">
      <div [class]="spinnerClass()"></div>
      @if (message()) {
        <p class="text-sm text-gray-600">{{ message() }}</p>
      }
    </div>
  </div>
} @else {
  <div class="flex flex-col items-center justify-center gap-3 py-8">
    <div [class]="spinnerClass()"></div>
    @if (message()) {
      <p class="text-sm text-gray-600">{{ message() }}</p>
    }
  </div>
}
