// client/src/presentation/components/modal/Modal.jsx
const Modal = ({
    isOpen,
    onClose,
    title,
    children,
}) => {

    if (!isOpen) return null;

    return (

        <div className="fixed inset-0 bg-black/40 flex items-center justify-center">

            <div className="bg-white rounded-xl w-full max-w-lg shadow-lg">

                {/* Header */}

                <div className="flex justify-between items-center border-b p-4">

                    <h2>{title}</h2>

                    <button onClick={onClose}>
                        ✕
                    </button>

                </div>

                {/* Body */}

                <div className="p-6">

                    {children}

                </div>

            </div>

        </div>

    );

};

export default Modal;

// client/src/app/shared/components/modal/modal.component.ts
import { Component, input, output, computed, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-modal',
  standalone: true,
  templateUrl: './modal.component.html',
  styleUrl: './modal.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ModalComponent {
  readonly isOpen = input(false);
  readonly title = input('');
  readonly size = input<'sm' | 'md' | 'lg' | 'xl'>('md');

  readonly closed = output<void>();

  readonly sizeClass = computed(() => {
    const sizes: Record<string, string> = {
      sm: 'max-w-sm',
      md: 'max-w-md',
      lg: 'max-w-lg',
      xl: 'max-w-xl',
    };
    return sizes[this.size()];
  });

  onBackdropClick(): void {
    this.closed.emit();
  }

  onClose(): void {
    this.closed.emit();
  }
}

@if (isOpen()) {
  <div class="fixed inset-0 z-50 flex items-center justify-center">
    <div class="fixed inset-0 bg-black/50 transition-opacity" (click)="onBackdropClick()"></div>
    <div
      [class]="'relative bg-white rounded-xl shadow-xl z-10 w-full mx-4 max-h-[90vh] overflow-y-auto ' + sizeClass"
    >
      <div class="flex items-center justify-between p-4 border-b border-gray-200">
        <h3 class="text-lg font-semibold text-gray-900">{{ title() }}</h3>
        <button
          class="p-1 rounded-lg hover:bg-gray-100 transition-colors"
          (click)="onClose()"
        >
          <svg class="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="p-4">
        <ng-content />
      </div>
    </div>
  </div>
}
