// client/src/app/shared/components/pagination/pagination.component.ts
import { Component, input, output, computed, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-pagination',
  standalone: true,
  templateUrl: './pagination.component.html',
  styleUrl: './pagination.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaginationComponent {
  readonly currentPage = input(1);
  readonly totalPages = input(1);
  readonly totalItems = input(0);
  readonly pageSize = input(10);

  readonly pageChanged = output<number>();

  readonly pages = computed(() => {
    const total = this.totalPages();
    const current = this.currentPage();
    const pages: (number | '...')[] = [];

    if (total <= 7) {
      for (let i = 1; i <= total; i++) pages.push(i);
    } else {
      pages.push(1);
      if (current > 3) pages.push('...');
      for (let i = Math.max(2, current - 1); i <= Math.min(total - 1, current + 1); i++) {
        pages.push(i);
      }
      if (current < total - 2) pages.push('...');
      pages.push(total);
    }

    return pages;
  });

  readonly hasPrevious = computed(() => this.currentPage() > 1);
  readonly hasNext = computed(() => this.currentPage() < this.totalPages());

  goToPage(page: number | '...'): void {
    if (page === '...') return;
    if (page >= 1 && page <= this.totalPages()) {
      this.pageChanged.emit(page);
    }
  }

  previousPage(): void {
    if (this.hasPrevious()) {
      this.pageChanged.emit(this.currentPage() - 1);
    }
  }

  nextPage(): void {
    if (this.hasNext()) {
      this.pageChanged.emit(this.currentPage() + 1);
    }
  }
}

<div class="flex items-center justify-between px-2 py-3">
  <p class="text-sm text-gray-600">
    Showing page {{ currentPage() }} of {{ totalPages() }} ({{ totalItems() }} items)
  </p>
  <nav class="flex items-center gap-1">
    <button
      class="px-3 py-1.5 text-sm rounded-lg border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      [disabled]="!hasPrevious()"
      (click)="previousPage()"
    >
      Previous
    </button>
    @for (page of pages(); track $index) {
      @if (page === '...') {
        <span class="px-2 py-1 text-gray-400">...</span>
      } @else {
        <button
          class="px-3 py-1.5 text-sm rounded-lg border transition-colors"
          [class]="page === currentPage() ? 'bg-indigo-600 text-white border-indigo-600' : 'border-gray-300 hover:bg-gray-50'"
          (click)="goToPage(page)"
        >
          {{ page }}
        </button>
      }
    }
    <button
      class="px-3 py-1.5 text-sm rounded-lg border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      [disabled]="!hasNext()"
      (click)="nextPage()"
    >
      Next
    </button>
  </nav>
</div>

// frontend/components/search/Pagination.tsx
import React from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";

interface PaginationProps {
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
}

export default function Pagination({ currentPage, totalPages, onPageChange }: PaginationProps) {
  const pages = Array.from({ length: totalPages }, (_, idx) => idx + 1);

  return (
    <div className="flex items-center justify-center gap-2 py-6 border-t border-slate-100 select-none">
      {/* Prev Button */}
      <button
        onClick={() => onPageChange(Math.max(1, currentPage - 1))}
        disabled={currentPage === 1}
        type="button"
        className="inline-flex items-center justify-center size-9 rounded-xl border border-slate-200 bg-white text-slate-500 hover:text-slate-800 hover:border-slate-350 disabled:opacity-40 disabled:pointer-events-none transition cursor-pointer"
        aria-label="Previous page"
      >
        <ChevronLeft className="size-4" />
      </button>

      {/* Pages indexes list */}
      {pages.map((p) => {
        const isCurrent = currentPage === p;
        return (
          <button
            key={p}
            onClick={() => onPageChange(p)}
            type="button"
            className={`inline-flex items-center justify-center size-9 rounded-xl text-xs sm:text-sm font-extrabold transition cursor-pointer ${
              isCurrent
                ? "bg-slate-900 text-white shadow-xs"
                : "border border-slate-200 bg-white text-slate-650 hover:border-slate-350 hover:bg-slate-50"
            }`}
          >
            {p}
          </button>
        );
      })}

      {/* Next Button */}
      <button
        onClick={() => onPageChange(Math.min(totalPages, currentPage + 1))}
        disabled={currentPage === totalPages}
        type="button"
        className="inline-flex items-center justify-center size-9 rounded-xl border border-slate-200 bg-white text-slate-500 hover:text-slate-800 hover:border-slate-350 disabled:opacity-40 disabled:pointer-events-none transition cursor-pointer"
        aria-label="Next page"
      >
        <ChevronRight className="size-4" />
      </button>
    </div>
  );
}
