// client/src/app/admin/features/login/login.component.ts
import { Component, inject, ChangeDetectionStrategy, computed } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../shared/services/auth.service';
import { ButtonComponent } from '../../../shared/components/button/button.component';
import { InputComponent } from '../../../shared/components/input/input.component';

@Component({
  selector: 'app-admin-login',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, ButtonComponent, InputComponent],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoginComponent {
  private readonly fb = inject(FormBuilder);
  private readonly router = inject(Router);
  private readonly authService = inject(AuthService);
  readonly loading = this.authService.loading;
  readonly pendingVerificationEmail = this.authService.pendingVerificationEmail;

  readonly showVerifyButton = computed(() => this.pendingVerificationEmail() !== null);

  readonly form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]],
  });

  onSubmit(): void {
    if (this.form.valid) { this.authService.adminLogin(this.form.getRawValue()); }
    else { this.form.markAllAsTouched(); }
  }

  onVerify(): void {
    const email = this.pendingVerificationEmail();
    if (email) {
      this.authService.clearPendingVerification();
      this.authService.resendOtp({ email }).subscribe({
        next: () => {
          this.router.navigate(['/verify-email'], {
            queryParams: { email, portal: 'admin' },
          });
        },
      });
    }
  }
}

<div class="min-h-screen flex items-center justify-center bg-surface-dark px-4 relative overflow-hidden">

  <!-- Background dot grid -->
  <div class="absolute inset-0 opacity-[0.035]"
    style="background-image: radial-gradient(circle, #C9A84C 1px, transparent 1px); background-size: 28px 28px;"></div>

  <!-- Gold glow top -->
  <div class="absolute top-0 left-1/2 -translate-x-1/2 w-150 h-75 bg-accent-500/10 rounded-full blur-3xl pointer-events-none"></div>

  <!-- Card -->
  <div class="relative w-full max-w-md">

    <!-- Logo / Brand -->
    <div class="text-center mb-8">
      <div class="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-linear-to-br from-accent-500 to-accent-600 shadow-lg shadow-accent-500/20 mb-5">
        <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.75"
            d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/>
        </svg>
      </div>
      <h1 class="font-heading text-2xl font-bold text-white tracking-tight">BookMyVenue</h1>
      <p class="text-blue-200/40 text-xs tracking-widest uppercase font-semibold mt-1">Admin Control Panel</p>
    </div>

    <!-- Form card -->
    <div class="bg-surface-dark2 rounded-2xl border border-[#1A3050] shadow-2xl p-8">

      <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4">
        <div>
          <label class="block text-xs font-semibold text-blue-200/60 uppercase tracking-widest mb-1.5">
            Email Address
          </label>
          <app-input
            type="email"
            formControlName="email"
            [required]="true"
            placeholder="admin@bookmyvenue.com"
            [error]="form.controls.email.touched && form.controls.email.errors ? 'Enter a valid email address' : ''"
          />
        </div>

        <div>
          <label class="block text-xs font-semibold text-blue-200/60 uppercase tracking-widest mb-1.5">
            Password
          </label>
          <app-input
            type="password"
            formControlName="password"
            [required]="true"
            placeholder="••••••••"
            [error]="form.controls.password.touched && form.controls.password.errors ? 'Minimum 6 characters' : ''"
          />
        </div>

        <div class="flex justify-end pt-1">
          <a routerLink="/admin/forgot-password"
            class="text-xs text-blue-200/50 hover:text-accent-500 transition-colors">
            Forgot password?
          </a>
        </div>

        <app-button label="Sign In to Admin" type="submit" [loading]="loading()" [fullWidth]="true" />

        @if (showVerifyButton()) {
          <app-button
            label="Verify Email"
            type="button"
            (clicked)="onVerify()"
            [fullWidth]="true"
            variant="outline"
            class="mt-3"
          />
        }
      </form>
    </div>

    <!-- Footer note -->
    <p class="text-center text-xs text-blue-200/25 mt-6">
      &copy; 2026 BookMyVenue · All activity is logged and monitored
    </p>
  </div>
</div>

// frontend/src/app/(auth)/login/page.tsx
import type { Metadata } from "next";
import Link from "next/link";

import {
  AuthBrand,
  AuthDivider,
  AuthSplitLayout,
  GoogleIcon,
  inputClassName,
} from "@/components/auth/auth-split-layout";
import { AuthForm } from "@/components/auth/auth-form";
import { PasswordField } from "@/components/auth/password-field";

export const metadata: Metadata = {
  title: "Login | BookMyVenue",
  description: "Sign in to your BookMyVenue account",
};

export default function LoginPage() {
  return (
    <AuthSplitLayout>
      <div className="w-full max-w-md space-y-8">
        <AuthBrand
          title="Welcome back"
          description="Please enter your details to sign in."
        />

        <AuthForm className="space-y-6">
          <div className="space-y-4">
            <div className="space-y-1.5">
              <label className="text-label-md text-on-surface" htmlFor="email">
                Email Address
              </label>
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                placeholder="name@company.com"
                className={inputClassName}
              />
            </div>

            <PasswordField id="password" label="Password" />
          </div>

          <div className="flex items-center justify-between">
            <label className="group flex cursor-pointer items-center gap-2">
              <div className="relative flex items-center">
                <input
                  type="checkbox"
                  name="remember"
                  className="peer size-5 cursor-pointer appearance-none rounded-md border border-border-subtle transition-all checked:border-primary-container checked:bg-primary-container"
                />
                <span
                  className="pointer-events-none absolute top-1/2 left-1/2 size-4 -translate-x-1/2 -translate-y-1/2 text-white opacity-0 peer-checked:opacity-100"
                  aria-hidden
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                    <path d="M5 12l5 5L19 7" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </span>
              </div>
              <span className="text-label-md text-text-muted transition-colors group-hover:text-on-surface">
                Remember me
              </span>
            </label>
            <Link
              href="#"
              className="text-label-md font-semibold text-primary-container decoration-2 underline-offset-4 hover:underline"
            >
              Forgot password?
            </Link>
          </div>

          <div className="space-y-4 pt-2">
            <button
              type="submit"
              className="w-full rounded-full bg-primary-container py-4 text-label-md text-white shadow-lg shadow-primary-container/20 transition-all duration-200 hover:-translate-y-0.5 active:scale-[0.98]"
            >
              Sign In
            </button>

            <AuthDivider />

            <button
              type="button"
              className="flex w-full items-center justify-center gap-3 rounded-full border border-border-subtle bg-white py-3.5 transition-all duration-200 hover:bg-stone-50 active:scale-[0.98]"
            >
              <GoogleIcon />
              <span className="text-label-md text-on-surface">
                Continue with Google
              </span>
            </button>
          </div>
        </AuthForm>

        <div className="pt-8 text-center">
          <p className="text-body-md text-text-muted">
            Don&apos;t have an account?{" "}
            <Link
              href="/signup"
              className="ml-1 font-bold text-primary-container decoration-2 underline-offset-4 hover:underline"
            >
              Sign up
            </Link>
          </p>
        </div>
      </div>
    </AuthSplitLayout>
  );
}
