// client/src/presentation/components/common/Pagination.jsx
import { ChevronLeft, ChevronRight } from "lucide-react";

const Pagination = ({
    currentPage,
    totalPages,
    onPageChange,
}) => {

    if (totalPages <= 1) return null;

    const pages = [];

    for (let i = 1; i <= totalPages; i++) {
        pages.push(i);
    }

    return (

        <div className="flex items-center justify-between mt-6">

            {/* Previous Button */}

            <button
                onClick={() => onPageChange(currentPage - 1)}
                disabled={currentPage === 1}
                className="flex items-center gap-2 px-4 py-2 border rounded-lg disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-100"
            >
                <ChevronLeft size={18} />
                Previous
            </button>

            {/* Page Numbers */}

            <div className="flex items-center gap-2">

                {pages.map((page) => (

                    <button
                        key={page}
                        onClick={() => onPageChange(page)}
                        className={`w-10 h-10 rounded-lg transition-all
                            ${
                                currentPage === page
                                    ? "bg-[#FF8C1A] text-white"
                                    : "border hover:bg-gray-100"
                            }`}
                    >
                        {page}
                    </button>

                ))}

            </div>

            {/* Next Button */}

            <button
                onClick={() => onPageChange(currentPage + 1)}
                disabled={currentPage === totalPages}
                className="flex items-center gap-2 px-4 py-2 border rounded-lg disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-100"
            >
                Next
                <ChevronRight size={18} />
            </button>

        </div>

    );

};

export default Pagination;

// client/src/app/shared/components/pagination/pagination.component.ts
import { Component, input, output, computed, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-pagination',
  standalone: true,
  templateUrl: './pagination.component.html',
  styleUrl: './pagination.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaginationComponent {
  readonly currentPage = input(1);
  readonly totalPages = input(1);
  readonly totalItems = input(0);
  readonly pageSize = input(10);

  readonly pageChanged = output<number>();

  readonly pages = computed(() => {
    const total = this.totalPages();
    const current = this.currentPage();
    const pages: (number | '...')[] = [];

    if (total <= 7) {
      for (let i = 1; i <= total; i++) pages.push(i);
    } else {
      pages.push(1);
      if (current > 3) pages.push('...');
      for (let i = Math.max(2, current - 1); i <= Math.min(total - 1, current + 1); i++) {
        pages.push(i);
      }
      if (current < total - 2) pages.push('...');
      pages.push(total);
    }

    return pages;
  });

  readonly hasPrevious = computed(() => this.currentPage() > 1);
  readonly hasNext = computed(() => this.currentPage() < this.totalPages());

  goToPage(page: number | '...'): void {
    if (page === '...') return;
    if (page >= 1 && page <= this.totalPages()) {
      this.pageChanged.emit(page);
    }
  }

  previousPage(): void {
    if (this.hasPrevious()) {
      this.pageChanged.emit(this.currentPage() - 1);
    }
  }

  nextPage(): void {
    if (this.hasNext()) {
      this.pageChanged.emit(this.currentPage() + 1);
    }
  }
}

<div class="flex items-center justify-between px-2 py-3">
  <p class="text-sm text-gray-600">
    Showing page {{ currentPage() }} of {{ totalPages() }} ({{ totalItems() }} items)
  </p>
  <nav class="flex items-center gap-1">
    <button
      class="px-3 py-1.5 text-sm rounded-lg border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      [disabled]="!hasPrevious()"
      (click)="previousPage()"
    >
      Previous
    </button>
    @for (page of pages(); track $index) {
      @if (page === '...') {
        <span class="px-2 py-1 text-gray-400">...</span>
      } @else {
        <button
          class="px-3 py-1.5 text-sm rounded-lg border transition-colors"
          [class]="page === currentPage() ? 'bg-indigo-600 text-white border-indigo-600' : 'border-gray-300 hover:bg-gray-50'"
          (click)="goToPage(page)"
        >
          {{ page }}
        </button>
      }
    }
    <button
      class="px-3 py-1.5 text-sm rounded-lg border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      [disabled]="!hasNext()"
      (click)="nextPage()"
    >
      Next
    </button>
  </nav>
</div>
