// apps/owner-portal/src/components/Pagination.tsx
import React from 'react'

interface PaginationProps {
  page: number
  perPage: number
  total: number
  totalPages: number
  setPage: React.Dispatch<React.SetStateAction<number>>
}

export function Pagination({ page, perPage, total, totalPages, setPage }: PaginationProps) {
  if (totalPages <= 1) return null

  const start = (page - 1) * perPage + 1
  const end = Math.min(page * perPage, total)

  return (
    <div className="flex items-center justify-between border-t border-zinc-200 dark:border-ink-700 px-6 py-4 bg-white dark:bg-ink-900 rounded-b-xl">
      <div className="text-sm text-zinc-500 dark:text-zinc-400 font-medium">
        {start}&ndash;{end} of {total}
      </div>
      
      <div className="flex items-center gap-4">
        <button
          onClick={() => setPage(p => Math.max(1, p - 1))}
          disabled={page <= 1}
          className="px-4 py-1.5 border border-zinc-200 dark:border-ink-700 bg-white dark:bg-ink-900 hover:bg-zinc-50 dark:hover:bg-ink-800 rounded-lg text-sm font-medium text-zinc-700 dark:text-zinc-300 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Previous
        </button>
        
        <span className="text-sm text-zinc-500 dark:text-zinc-400 font-medium">
          Page {page} of {totalPages}
        </span>
        
        <button
          onClick={() => setPage(p => Math.min(totalPages, p + 1))}
          disabled={page >= totalPages}
          className="px-4 py-1.5 border border-zinc-200 dark:border-ink-700 bg-white dark:bg-ink-900 hover:bg-zinc-50 dark:hover:bg-ink-800 rounded-lg text-sm font-medium text-zinc-700 dark:text-zinc-300 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Next
        </button>
      </div>
    </div>
  )
}

// client/src/app/shared/components/pagination/pagination.component.ts
import { Component, input, output, computed, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-pagination',
  standalone: true,
  templateUrl: './pagination.component.html',
  styleUrl: './pagination.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaginationComponent {
  readonly currentPage = input(1);
  readonly totalPages = input(1);
  readonly totalItems = input(0);
  readonly pageSize = input(10);

  readonly pageChanged = output<number>();

  readonly pages = computed(() => {
    const total = this.totalPages();
    const current = this.currentPage();
    const pages: (number | '...')[] = [];

    if (total <= 7) {
      for (let i = 1; i <= total; i++) pages.push(i);
    } else {
      pages.push(1);
      if (current > 3) pages.push('...');
      for (let i = Math.max(2, current - 1); i <= Math.min(total - 1, current + 1); i++) {
        pages.push(i);
      }
      if (current < total - 2) pages.push('...');
      pages.push(total);
    }

    return pages;
  });

  readonly hasPrevious = computed(() => this.currentPage() > 1);
  readonly hasNext = computed(() => this.currentPage() < this.totalPages());

  goToPage(page: number | '...'): void {
    if (page === '...') return;
    if (page >= 1 && page <= this.totalPages()) {
      this.pageChanged.emit(page);
    }
  }

  previousPage(): void {
    if (this.hasPrevious()) {
      this.pageChanged.emit(this.currentPage() - 1);
    }
  }

  nextPage(): void {
    if (this.hasNext()) {
      this.pageChanged.emit(this.currentPage() + 1);
    }
  }
}

<div class="flex items-center justify-between px-2 py-3">
  <p class="text-sm text-gray-600">
    Showing page {{ currentPage() }} of {{ totalPages() }} ({{ totalItems() }} items)
  </p>
  <nav class="flex items-center gap-1">
    <button
      class="px-3 py-1.5 text-sm rounded-lg border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      [disabled]="!hasPrevious()"
      (click)="previousPage()"
    >
      Previous
    </button>
    @for (page of pages(); track $index) {
      @if (page === '...') {
        <span class="px-2 py-1 text-gray-400">...</span>
      } @else {
        <button
          class="px-3 py-1.5 text-sm rounded-lg border transition-colors"
          [class]="page === currentPage() ? 'bg-indigo-600 text-white border-indigo-600' : 'border-gray-300 hover:bg-gray-50'"
          (click)="goToPage(page)"
        >
          {{ page }}
        </button>
      }
    }
    <button
      class="px-3 py-1.5 text-sm rounded-lg border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      [disabled]="!hasNext()"
      (click)="nextPage()"
    >
      Next
    </button>
  </nav>
</div>
